import type { Metadata } from 'next';
import { inter, lexend } from '~/app/fonts';
import { ThemeProvider } from '~/components/theme-provider';
import { isMobileDevice } from '~/lib/is-mobile-device';
import './globals.css';

export const metadata: Metadata = {
  title: '智能知识库',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const isMobile = await isMobileDevice();

  return (
    <html
      lang="zh"
      className={`h-full scroll-smooth ${inter.variable} ${inter.className} ${lexend.className}`}
    >
      <body className="flex h-full flex-col">
        {isMobile && (
          <div className="flex h-screen flex-col items-center justify-center">
            <p>暂不支持移动端浏览器~</p>
          </div>
        )}
        {!isMobile && (
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            {children}
          </ThemeProvider>
        )}
      </body>
    </html>
  );
}
