import type { Metadata } from 'next';
import { inter, lexend } from '~/app/fonts';
import './globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${inter.className} ${lexend.className}`}
      >
        {children}
      </body>
    </html>
  );
}

// function render() {}

// // 独立运行时
// if (typeof window === 'object' && !window.__POWERED_BY_QIANKUN__) {
//   render();
// }

// export async function bootstrap() {
//   console.log('next app bootstraped');
// }

// export async function mount(props) {}
// export async function unmount(props) {}
