name: deploy ec2

on:
  push:
    branches:
      - poc

jobs:
  Deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Build & Deploy
        env:
          PRIVATE_KEY: ${{ secrets.EC2_PEM }}
          HOSTNAME: ${{secrets.EC2_IP}}
          USER_NAME: ${{secrets.EC2_USER}}

        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} '
            # Now we have got the access of EC2 and we will start the deploy .
            cd ~/knowledge-ai/ knowledge-web/ ;
            echo '------ cd done ------' ;
            git checkout poc ;
            git checkout . ;
            git pull origin poc ;
            echo '------ git pull done ------' ;
            docker rm $(docker stop $(docker ps -a -q --filter ancestor= knowledge-web-docker)) ;
            echo '------ docker rm done ------' ;
            docker build -t  knowledge-web-docker . ;
            echo '------ docker build done ------'
            docker run -d -p 0.0.0.0:4000:4000  knowledge-web-docker ;
            echo '------ docker run done ------' ;
            '
          rm -rf private_key
